console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'
version = 3

[transient_prompt]
  template = '❯ '
  foreground = '#B48EAD'
  foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = '#FD971E'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#98E025'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#FFAFD7>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#6C6C6C'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_ahead_icon = '<#88C0D0>⇡ </>'
      branch_behind_icon = '<#88C0D0>⇣ </>'
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = '#A3BE8C'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = '#B48EAD'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
