      console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'
version = 3

[transient_prompt]
  template = '❯ '
  foreground = '#9ECE6A'
  foreground_templates = ['{{ if gt .Code 0 }}#F7768E{{ end }}']

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  # Segment 1: User (Green) @ Hostname (True Gray)
  [[blocks.segments]]
    # We set the base foreground to Green for the user
    # We use <#858585> to force the @ and Hostname to be Gray
    template = '{{ .UserName }}<#858585>@{{ .HostName }}</> '
    foreground = '#9ECE6A'
    type = 'session'
    style = 'plain'

  # Segment 2: Path (Orange)
  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#FF9E64'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # Segment 3: Prompt symbol (Green -> Red on error)
  [[blocks.segments]]
    template = '❯ '
    foreground = '#9ECE6A'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#F7768E{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
