# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[‚ñ∏‚ñπ ](dimmed white)"

format = """( $directory$nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
${custom.jj}\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$memory_uasge\
$status\
$os\
$battery\
$time """

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[‚óé](bold italic bright-yellow)"
error_symbol = "[‚óã](italic purple)"
vimcmd_symbol = "[‚ñ†](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "‚óå"
vimcmd_replace_symbol = "‚ñ°"
vimcmd_visual_symbol = "‚ñº"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "‚ãà‚îà"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[‚≠ò $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "~"
truncation_length = 4
truncation_symbol = "../"
read_only = " ‚óà"
use_os_path_sep = true
style = "bold green"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold green'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
format = "[‚óÑ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[‚ñ∂](blue italic)"

[localip]
ssh_only = true
format = " ‚óØ[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%-I:%M%p"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "‚ñà"
charging_symbol = "[‚Üë](italic bold green)"
discharging_symbol = "‚Üì"
unknown_symbol = "‚ñë"
empty_symbol = "‚ñÉ"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

# custom module for jj status
[custom.jj]
description = "The current jj status"
when = "jj --ignore-working-copy root"
symbol = "ü•ã "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "üí•"),
      if(divergent, "üöß"),
      if(hidden, "üëª"),
      if(immutable, "üîí"),
    ),
    raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
    raw_escape_sequence("\x1b[1;32m") ++ coalesce(
      truncate_end(29, description.first_line(), "‚Ä¶"),
      "(no description set)",
    ) ++ raw_escape_sequence("\x1b[0m"),
  )
'
'''

# optionally disable git modules when JJ is found.
# note that you'll need to add ${custom.git_branch}, ${custom.git_commit} etc
# into format: https://starship.rs/config/#default-prompt-format
[git_status]
disabled = true

[custom.git_status]
when = "! jj --ignore-working-copy root"
command = "starship module git_status"
style = "" # This disables the default "(bold green)" style
description = "Only show git_status if we're not in a jj repo"

[git_commit]
disabled = true

[custom.git_commit]
when = "! jj --ignore-working-copy root"
command = "starship module git_commit"
style = ""
description = "Only show git_commit if we're not in a jj repo"

[git_metrics]
disabled = true

[custom.git_metrics]
when = "! jj --ignore-working-copy root"
command = "starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"
style = ""

[git_branch]
disabled = true

[custom.git_branch]
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"
style = ""

# [git_branch]
# format = " [$branch(:$remote_branch)]($style)"
# symbol = "[‚ñ≥](bold italic bright-blue)"
# style = "italic bright-blue"
# truncation_symbol = "‚ãØ"
# truncation_length = 11
# ignore_branches = ["main", "master"]
# only_attached = true

# [git_metrics]
# format = '([‚ñ¥$added]($added_style))([‚ñø$deleted]($deleted_style))'
# added_style = 'italic dimmed green'
# deleted_style = 'italic dimmed red'
# ignore_submodules = true
# disabled = false

# [git_status]
# style = "bold italic bright-blue"
# format = "([‚é™$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed‚é•]($style))"
# conflicted = "[‚ó™‚ó¶](italic bright-magenta)"
# ahead = "[‚ñ¥‚îÇ[${count}](bold white)‚îÇ](italic green)"
# behind = "[‚ñø‚îÇ[${count}](bold white)‚îÇ](italic red)"
# diverged = "[‚óá ‚ñ¥‚î§[${ahead_count}](regular white)‚îÇ‚ñø‚î§[${behind_count}](regular white)‚îÇ](italic bright-magenta)"
# untracked = "[‚óå‚ó¶](italic bright-yellow)"
# stashed = "[‚óÉ‚óà](italic white)"
# modified = "[‚óè‚ó¶](italic yellow)"
# staged = "[‚ñ™‚î§[$count](bold white)‚îÇ](italic bright-cyan)"
# renamed = "[‚óé‚ó¶](italic bright-blue)"
# deleted = "[‚úï](italic red)"

[deno]
disabled = true
format = " [deno](italic) [‚à´ $version](green bold)"
version_format = "${raw}"

[lua]
disabled = true
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "‚®Ä "
style = "bold bright-yellow"

[nodejs]
disabled = true
format = " [node](italic) [‚ó´ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
disabled = true
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "[‚åâ](bold bright-blue)‚åä "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
disabled = true
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = "‚óÜ "
version_format = "${raw}"
style = "bold red"

[rust]
disabled = true
format = " [rs](italic) [$symbol$version]($style)"
symbol = ""
version_format = "${raw}"
style = "bold red"

[package]
disabled = true
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "‚ó® "
style = "dimmed yellow italic bold"

[swift]
disabled = true
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = "‚óÅ "
style = "bold bright-red"
version_format = "${raw}"

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = "‚ñ≤ "

[buf]
disabled = true
symbol = "‚ñ† "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
disabled = true
symbol = "‚ÑÇ "
format = " [$symbol($version(-$name))]($style)"

[cpp]
disabled = true
symbol = "‚ÑÇ "
format = " [$symbol($version(-$name))]($style)"

[conda]
disabled = true
symbol = "‚óØ "
format = " conda [$symbol$environment]($style)"

[pixi]
disabled = true
symbol = "‚ñ† "
format = " pixi [$symbol$version ($environment )]($style)"

[dart]
disabled = true
symbol = "‚óÅ‚óÖ "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = "‚óß "
format = " docker [$symbol$context]($style)"

[elixir]
disabled = true
symbol = "‚ñ≥ "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
disabled = true
symbol = "‚ó© "
format = " elm [$symbol($version )]($style)"

[golang]
disabled = true
symbol = "‚à© "
format = " go [$symbol($version )]($style)"

[haskell]
disabled = true
symbol = "‚ùØŒª "
format = " hs [$symbol($version )]($style)"

[java]
disabled = true
symbol = "‚à™ "
format = " java [${symbol}(${version} )]($style)"

[julia]
disabled = true
symbol = "‚óé "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "‚ñ™‚ñ´‚ñ™ "
format = " mem [${ram}( ${swap})]($style)"

[nim]
disabled = true
symbol = "‚ñ¥‚ñ≤‚ñ¥ "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = ''
format = '[$symbol nix ‚é™]($style) [$name](italic dimmed white)'

[spack]
symbol = "‚óá "
format = " spack [$symbol$environment]($style)"
